// <auto-generated />
namespace MVCSamp_FilmReview.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ReviewScoreImp31 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ReviewScoreImp31));
        
        string IMigrationMetadata.Id
        {
            get { return "202008311650336_ReviewScoreImp31"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
